- name: installing apache2
  hosts: all
  become: yes
  tasks:
  -  name: uninstall apache2  
     apt: 
       name: apache2
       state: present
       update_cache: true
  -  name: restarting apache2 service
     service: 
       name: apache2
       state: restarted       
           
